version: "3.8"
services:
  server:
    image: "nginx:stable-alpine" # official image
    ports:
      - "8000:80" # docs state that 80 is exposed by the container
    volumes: # we bind our conf to the container so we can write it on our hostmachine
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # docs tell you to put your conf in this dir on the container. set to readonly with ro since our config should not change from inside the container
  php:
    # we need a keyed config for build since we're specifying a dockerfile nested in our folder structure and of a different name
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      # create bind mount to work on src code on our machine and have it update on the container
      - ./src:/var/www/html:delegated # delegated means if container writes to this location, writes are batched which makes for better performance - use when container should not write frequently or instant update is not required
  mysql:
    image: mysql:5.7 # official image
    # provide env variables used by images to setup user pw and database from docs
    env_file:
      - ./env/mysql.env

  # # utility containers
  # composer:
  # artisan:
  # npm:
