version: "3.8"
services:
  server:
    image: "nginx:stable-alpine" # official image
    ports:
      - "8000:80" # docs state that 80 is exposed by the container
    volumes: # we bind our conf to the container so we can write it on our hostmachine
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # docs tell you to put your conf in this dir on the container. set to readonly with ro since our config should not change from inside the container
  # php:
  # mysql:
  # # utility containers
  # composer:
  # artisan:
  # npm:
