apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  type: ClusterIP # does not expose auth container to outside world (user pod uses LoadBalancer)
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
