apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80 # only port for users container is exposed to outside world (auth container is listening on port 80)
      targetPort: 80
