apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: brentgrammer/kub-demo-users:latest
          env: # injected into endpoint to use to communicate with auth container
            - name: AUTH_ADDRESS
              value: "auth-service.default"
