apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080 # only port for users container is exposed to outside world (auth container is listening on port 80)
      targetPort: 8080
